### ISSUE TITLE
Symbol not found error during fuel-indexer run command

### ISSUE THREAD

**Issue by lzhabo** [FuelLabs/fuel-indexer#975]
In my repo with my custom scheme for indexing logs - link [here](https://github.com/compolabs/spark-indexer/tree/fuel-indexer) I tried to run `run` command but face error like this. 

Command : 
```
fuel-indexer run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --postgres-host 127.0.0.1 --postgres-port 5432  --postgres-password mysecretpassword --postgres-user postgres
```

Error message: 
```dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/lidia/.fuelup/toolchains/latest-aarch64-apple-darwin/bin/fuel-indexer (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
fish: Job 1, 'fuel-indexer run --run-migrat...' terminated by signal SIGABRT (Abort)
```
Fuel up versions

```
installed toolchains
--------------------
beta-1-aarch64-apple-darwin
beta-3-aarch64-apple-darwin
latest-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin
my-custom-toolchain

active toolchain
-----------------
latest-aarch64-apple-darwin (default)
  forc : 0.40.1
    - forc-client
      - forc-deploy : 0.40.1
      - forc-run : 0.40.1
    - forc-doc : 0.40.1
    - forc-explore : 0.28.1
    - forc-fmt : 0.40.1
    - forc-index : 0.16.0
    - forc-lsp : 0.40.1
    - forc-tx : 0.40.1
    - forc-wallet : 0.2.2
  fuel-core : Error getting version string
  fuel-indexer : Error getting version string

fuels versions
---------------
forc : 0.42
```

**Comment by ra0x3** [comment]
@lzhabo 
- Could you post the full error output? (the ugly WASM error?).

**Comment by lzhabo** [comment]
@ra0x3 this is full text error

**Comment by ra0x3** [comment]
> @ra0x3 this is full text error

- Got it. 
- There was a small bug in 0.16.0 🥲 which adds the incorrect dependency (`native-execution`) to default indexers
  - This is fixed in 0.16.1
- I have a tiny fix I'd like to push to your `fuel-indexer` branch 
  - This commit also shows the proper way to get a certain transaction type

**Comment by lzhabo** [comment]
@ra0x3 added you as collaborator to spark-indexer repo

**Comment by lzhabo** [comment]
@ra0x3 also updated forc-indexer to 0.16.1 v and error is still same 


```
 fuelup default latest                                                                                                                                        (fuel-indexer+7) 18:20:43 
default toolchain set to 'latest-aarch64-apple-darwin'
^^/spark-indexer >>> fuelup show                                                                                                                                                  (fuel-indexer+7) 18:21:01 
Default host: aarch64-apple-darwin
fuelup home: /Users/lidia/.fuelup

installed toolchains
--------------------
beta-1-aarch64-apple-darwin
beta-3-aarch64-apple-darwin
latest-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin
my-custom-toolchain

active toolchain
-----------------
latest-aarch64-apple-darwin (default)
  forc : 0.40.1
    - forc-client
      - forc-deploy : 0.40.1
      - forc-run : 0.40.1
    - forc-doc : 0.40.1
    - forc-explore : 0.28.1
    - forc-fmt : 0.40.1
    - forc-index : 0.16.1
    - forc-lsp : 0.40.1
    - forc-tx : 0.40.1
    - forc-wallet : 0.2.2
  fuel-core : Error getting version string
  fuel-indexer : Error getting version string

fuels versions
---------------
forc : 0.42
^^/spark-indexer >>> fuel-indexer run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --postgres-host 127.0.0.1 --postgres-port 5432  --postgres-password mysecretpassword --postgres-user postgres
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/lidia/.fuelup/toolchains/latest-aarch64-apple-darwin/bin/fuel-indexer (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

fish: Job 1, 'fuel-indexer run --run-migrat...' terminated by signal SIGABRT (Abort)

```

**Comment by chlenc** [comment]
@ra0x3 
For me build works well, but `fuel-indexer run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --postgres-host 127.0.0.1 --postgres-port 5432  --postgres-password mysecretpassword --postgres-user postgres` fails with this error (ofc I recreated docker container with database)
```
thread 'tokio-runtime-worker' panicked at 'Failed to put object.: Database(PgDatabaseError { severity: Error, code: "42703", message: "column \"id\" does not exist", detail: None, hint: None, position: Some(Original(443)), where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("parse_relation.c"), line: Some(3651), routine: Some("errorMissingColumn") })', packages/fuel-indexer/src/database.rs:157:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, 'fuel-indexer run --run-migratio…' terminated by signal SIGABRT (Abort)
```

**Comment by chlenc** [comment]
That's work for me ✅
Do you have any ideas on how to fix @lzhabo problem?

**Comment by ra0x3** [comment]
@chlenc 
- Ok this issue is about "Symbol not found error". 
- It looks like that issue is resolved, so we can close this
- If you have other questions, you would have to open up another issue :)
